import hashlib
import json
from typing import Callable, List, Optional

from physical_ai_runtime.core.feedback import SemanticFeedback
from physical_ai_runtime.ai.agent.action_schema import SemanticAction


class SemanticPlanner:
    """
    Semantic AI decision layer.

    The planner does NOT:
    - command joints
    - generate TCP coordinates
    - calculate correction distances
    - bypass runtime safety checks

    It chooses only a semantic action exposed by the runtime.
    """

    def __init__(
        self,
        reasoner: Callable,
    ):
        self.reasoner = reasoner
        self.history: List[dict] = []

        # Cache only previously AI-selected semantic decisions.
        # Manipulation/recovery motions are intentionally not cached.
        self._decision_cache = {}
        self._cacheable_actions = {
            "REOBSERVE",
            "ABORT",
        }

    @staticmethod
    def _feedback_cache_key(
        feedback: SemanticFeedback,
        available,
    ):
        payload = {
            "state": feedback.state,
            "object_id": feedback.object_id,
            "message": feedback.message,
            "confidence": feedback.confidence,
            "metrics": feedback.metrics,
            "available_actions": list(available),
        }

        encoded = json.dumps(
            payload,
            sort_keys=True,
            default=str,
            separators=(",", ":"),
        ).encode("utf-8")

        return hashlib.sha256(
            encoded
        ).hexdigest()

    def choose_action(
        self,
        feedback: SemanticFeedback,
    ) -> SemanticAction:

        available = (
            feedback.available_actions
            or []
        )

        if not available:
            return SemanticAction(
                action="ABORT",
                object_id=feedback.object_id,
                reason=(
                    "Runtime exposed no valid "
                    "recovery actions."
                ),
            )

        cache_key = self._feedback_cache_key(
            feedback,
            available,
        )

        cached = self._decision_cache.get(
            cache_key
        )

        if (
            cached is not None
            and cached.action in available
            and cached.action
                in self._cacheable_actions
        ):
            action = SemanticAction(
                action=cached.action,
                object_id=feedback.object_id,
                reason=(
                    "Reused previously AI-selected "
                    "semantic decision: "
                    + str(cached.reason)
                ),
                strategy=cached.strategy,
            )

            self.history.append({
                "feedback_state": feedback.state,
                "action": action.action,
                "reason": action.reason,
                "cached": True,
            })

            return action

        context = {
            "state": feedback.state,
            "object_id": feedback.object_id,
            "message": feedback.message,
            "confidence": feedback.confidence,
            "metrics": feedback.metrics,
            "available_actions": available,
            "history": self.history[-10:],
        }

        try:
            decision = self.reasoner(
                context
            )

            if isinstance(decision, str):
                action_name = decision
                reason = None
                strategy = None

            elif isinstance(decision, dict):
                action_name = decision.get(
                    "action"
                )
                reason = decision.get(
                    "reason"
                )
                strategy = decision.get(
                    "strategy"
                )

            else:
                raise RuntimeError(
                    "INVALID_PLANNER_RESPONSE"
                )

            if action_name not in available:
                raise RuntimeError(
                    "PLANNER_SELECTED_UNAVAILABLE_ACTION: "
                    f"{action_name}; "
                    f"available={available}"
                )

        except Exception as e:
            action_name = "ABORT"
            reason = (
                "Planner fail-safe triggered: "
                + str(e)
            )
            strategy = None

        action = SemanticAction(
            action=action_name,
            object_id=feedback.object_id,
            reason=reason,
            strategy=strategy,
        )

        # Only cache successful AI decisions that do not initiate
        # manipulation/recovery motion. Fail-safe ABORT generated by
        # an exception is intentionally not cached.
        if (
            action.action
            in self._cacheable_actions
            and not (
                action.reason
                and action.reason.startswith(
                    "Planner fail-safe triggered:"
                )
            )
        ):
            self._decision_cache[
                cache_key
            ] = action

        self.history.append(
            {
                "feedback_state":
                    feedback.state,
                "action":
                    action.action,
                "reason":
                    action.reason,
                "cached": False,
            }
        )

        return action
